### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by thatside** [berstend/hypertunnel#1]
First - thanks for new great tool!
I've been searching for an alternative to localtunnel/ngrok/beame.io for a long time and now here is one :)
But now it lacks only one feature - HTTPS support. As far as I remember, some web services require HTTPS on webhook URL. Do you have any plans for this?
(I do not know Node.js so I'm not sure if I may help with that but will do whatever is needed).

**Comment by berstend** [comment]
Hey there!

hypertunnel is a bit different than localtunnel/ngrok as it's a generic TCP/IP reverse proxy and not "only" a http reverse proxy. :-)

In order for https://tunneldomain to work, the tunnel service needs to terminate the SSL connection and inspect/rewrite http headers. hypertunnel (currently) doesn't do that by design, which has the benefit of being able to proxy any kind of TCP/IP traffic (e.g. ssh, custom protocols, etc.).

You could however terminate SSL on your local server and tunnel that through hypertunnel 😄 

```bash
npm i --save pem
```
```es6
// foo.js

const https = require('https')
const pem = require('pem')

pem.createCertificate({ days: 1, selfSigned: true }, function (err, keys) {
  if (err) { throw err  }
  https.createServer({ key: keys.serviceKey, cert: keys.certificate }, function (req, res) {
    res.end('o hai!')
  }).listen(1443)
})
```
```bash
node foo.js
# and
npx hypertunnel -p 1443
```
Results in this:

![image](https://user-images.githubusercontent.com/1368633/41245200-b2e1cf2e-6da7-11e8-82b2-935dd5032c09.png)

As you can tell the ssl certificate is self-signed and not trusted by others. So it depends on the web-services if they require a valid ssl certificate (some have an option to turn that off).

I could add additional https support to hypertunnel, but that would require adding a http reverse proxy alongside the generic TCP/IP proxy, which feels a little like a step backwards.

This should be the sweet spot of localtunnel/ngrok, what's your problem with them? :-)

Depending on how this project evolves I might consider adding https support, maybe I find an elegant way to support both generic TCP/IP tunneling as well as implementing optional SSL support for web servers.

**Comment by thatside** [comment]
Thank you for this thorough description!
I am not so experienced with full SSL flow and nuances (alongside with Node.js, hehe), but now I understands where the problem is.
The problem of localtunnel for me is that it is somehow buggy - most of the time the tunnel works for a couple of hours and crashes after that without releasing the custom domain name - which as you understand is a real pain in case of working with webhooks on local machine - you need to go through the interface of the service to change webhook/callback URL and so on. For ngrok the problem is the same - and I don't like it's pricing model since I don't need it all the time.

Nevertheless thank you for your work - maybe I'll have some time and contribute more :)

**Comment by berstend** [comment]
Thanks for the suggestion, will definitely consider it. If stability is a concern (haven't used locatunnel/ngrok for longer sessions) than there's potential here for a nice differentiator. :-)

**Comment by thatside** [comment]
For ngrok everything works OK (I haven't had any real issues with it), but for localtunnel everything isn't so shiny - and it would require some time to fix it so I decided to find any another solution :)

**Comment by berstend** [comment]
Good news @thatside - SSL support has now landed 😄 

```bash
❯❯❯ npx hypertunnel@latest -p 7777 --ssl
```

More info:
https://github.com/berstend/hypertunnel/#bonus-free-ssl-termination-https

**Comment by thatside** [comment]
Thank you @berstend!
I still have stuff to get acknowledged with but I'm glad I have a tool to stimulate the study :laughing:
